---
var_demofolder_name: "fed-ocp-demo"
var_cluster_info:
  - { name: cluster01, region: eu-west-3, destroy: true }
  - { name: cluster02, region: eu-central-1, destroy: true }
  - { name: cluster03, region: eu-west-1, destroy: true }
